#!/usr/bin/env sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

set -e

APP_HOME=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=$(basename -- "$0")

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
  die "ERROR: gradle-wrapper.jar not found at $CLASSPATH"
fi

GRADLE_WRAPPER_PROPERTIES=$APP_HOME/gradle/wrapper/gradle-wrapper.properties

JAVA_OPTS=${JAVA_OPTS:-}

exec java $DEFAULT_JVM_OPTS $JAVA_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

